<?xml version="1.0" encoding="utf-8"?>
<Project>

  <PropertyGroup>
    <Authors>tom-englert</Authors>
    <Company>tom-englert.de</Company>
    <Title Condition="'$(Title)' == ''">$(Product)</Title>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <GitHubOrganization>tom-englert</GitHubOrganization>
    <PackageId>$(MSBuildProjectName).Fody</PackageId>
    <LangVersion>latest</LangVersion>
    <PackageOutputPath>$(SolutionDir)nugets</PackageOutputPath>
    <Nullable>enable</Nullable>
    <DebugType>embedded</DebugType>
    <DebugSymbols>true</DebugSymbols>
    <EmbedUntrackedSources>true</EmbedUntrackedSources>
    <Deterministic>true</Deterministic>
  </PropertyGroup>

  <ItemGroup>
    <PackageIconFiles Include="$(SolutionDir)*icon*.png" />
    <PackageLicenseFiles Include="$(SolutionDir)*license*" />
  </ItemGroup>

  <PropertyGroup>
    <PackageIconFileName Condition="'$(PackageIconFileName)' == ''">@(PackageIconFiles->'%(Filename)%(Extension)')</PackageIconFileName>
    <PackageLicenseFileName Condition="'$(PackageLicenseFileName)' == ''">@(PackageLicenseFiles->'%(Filename)%(Extension)')</PackageLicenseFileName>
    <PackageProjectUrl>http://github.com/$(GitHubOrganization)/$(PackageId)</PackageProjectUrl>
    <PackageIcon>$(PackageIconFileName)</PackageIcon>
    <PackageLicenseFile>$(PackageLicenseFileName)</PackageLicenseFile>
  </PropertyGroup>

  <ItemGroup>
    <TfmSpecificPackageFile Include="build\*.targets" PackagePath="build" />
  </ItemGroup>
  
  <ItemGroup>
    <None Include="@(PackageIconFiles)" Link="$(PackageIconFileName)" Pack="true" PackagePath="\" />
    <None Include="@(PackageLicenseFiles)" Link="$(PackageLicenseFileName)" Pack="true" PackagePath="\" />
  </ItemGroup>

  <Target Name="LogTargetFramework" BeforeTargets="CoreCompile">
    <Message Text="TargetFramework: $(TargetFramework): ID=$(TargetFrameworkIdentifier), Version=$(TargetFrameworkVersion), Profile=$(TargetFrameworkProfile)" />
  </Target>

</Project>